### ISSUE TITLE
name shows wrong status when it is expired and has a running auction

### ISSUE THREAD

**Issue by marc0olo** [aeternity/ae_mdw#119] opened 2020-12-11 17:10 UTC
@skkw it seems like the middleware currently returns an active auction for `Dashu.chain`  when requesting all auctions. but when calling the `name` endpoint we get the status `name` for `Dashu.chain` instead of `auction`:

```
{
	"active": false,
	"hash": "nm_2AkGwrfhm9RsSBuD9E1hscKknYWZ138E8DgC8xPQGjXSkc4AhZ",
	"info": {
		"active_from": 177459,
		"auction_timeout": null,
		"claims": [
			4777742
		],
		"expire_height": 295869,
		"ownership": {
			"current": "ak_wfkC73Fw4tLgRQLRR3xyVv6tnrBiV1jkdZqE1Go5eDLAMPp99",
			"original": "ak_wfkC73Fw4tLgRQLRR3xyVv6tnrBiV1jkdZqE1Go5eDLAMPp99"
		},
		"pointers": {
			"account_pubkey": "ak_2MoUfgnF2uPB7VUrkSDPhdYt9Bj91VYR3h4A8B1HhXi1de9BAK"
		},
		"revoke": null,
		"transfers": [
			7746136,
			6856587
		],
		"updates": [
			10473195,
			10107868,
			10107493,
			10107444,
			10104937,
			10104775,
			10102622,
			10102222,
			10101606,
			10099034,
			10098747,
			10098280,
			10090917,
			10090910,
			10081283,
			9471523,
			9231074,
			7747605,
			5570613
		]
	},
	"name": "Dashu.chain",
	"previous": [],
	"status": "name"
}
```

**Comment by skkw** [comment] 2020-12-11 18:49
Hi @marc0olo,

  this is intended behavior, as expired name can be in auction again. 
But until the end of the auction it's not active and isn't resolvable - reason why "active" is false.

**Comment by marc0olo** [comment] 2020-12-11 18:55
@skkw it is in auction again. I am not talking about the attribute `active`. it is the `status` attribute which is wrong.

the **status** is `name` instead of `auction`.

**Comment by skkw** [comment] 2020-12-11 20:29
> it is the `status` attribute which is wrong.
> the value of **status** is `name` instead of `auction`.

Ok, I see now.

**Comment by skkw** [comment] 2021-03-25 13:21
This is fixed in https://github.com/aeternity/ae_mdw/releases/tag/1.0.4

**Closed by skkw** 2021-03-25 13:21 UTC
