### ISSUE TITLE
Websocket v2 is sending messages in batches

### ISSUE THREAD

**Issue by lukeromanowicz** [aeternity/ae_mdw#1366] opened 2023-05-30 06:34 UTC
Websocket v2 seems to be sending messages in batches rather than "fluently" as new microblocks are minted. Instead of getting an update every few second a user usually needs to wait between 5 and 30 seconds and receives a massive batch messages at once:

![image](https://github.com/aeternity/ae_mdw/assets/46789227/8793f8ae-0152-4fe0-b45d-4c542c3db361)

It's hurting the UX significantly. Is there any way to improve it apart from artificially throttling the updates on the client side?

**Comment by jyeshe** [comment] 2023-05-30 18:12
In the context of `v2` which encodes transactions like the `/txs` endpoint, there are two kinds of subscriptions in this regard, which depends on the `source` parameter. By default the `source` is `mdw` which means the Mdw will sync data, encode it as the endpoint and broadcast it. Since the sync happens in a batch mode, the messages is likely to be broadcasted very quickly.

However it's also possible to subscribe to `source: node` to receive the blocks and transactions as soon as they minted. The data here on the other hand cannot be encoded in a endpoint fashion since the Mdw doesn't have the data synced.

**Comment by jyeshe** [comment] 2023-05-30 18:19
An additional note for the expected behaviour is that the BEAM is well know for its effort to make latency as low and stable as possible. So in order to obtain a broadcasting in a more sparse way, the client should subscribe to the `node`.

**Comment by jyeshe** [comment] 2023-06-02 13:09
I am closing this issue since the Mdw is behaving as expected in both kinds of broadcasting: after mining (`source=node`) and after syncing (`source=mdw`).

**Closed by jyeshe** 2023-06-02 13:09 UTC

**Comment by lukeromanowicz** [comment] 2023-06-12 12:40
The issue applies also to the REST API

**Comment by jyeshe** [comment] 2023-06-12 14:51
REST API issue described here:  https://github.com/aeternity/ae_mdw/issues/1389
