### ISSUE TITLE
AEX-9 balances for account don't seem consistent

### ISSUE THREAD

**Issue by thepiwo** [aeternity/ae_mdw#186] opened 2021-06-11 09:57 UTC
https://testnet.aeternity.io/mdw/aex9/balances/ct_BxckqeNbTYH7ayohwsnyq8JeU6G49zDrZuLoVXjE4fKwzcyna

shows balance for account `ak_11111111111111111111111111111111273Yts`

https://testnet.aeternity.io/mdw/aex9/balances/account/ak_11111111111111111111111111111111273Yts

doesn't show any balances

**Comment by jyeshe** [comment] 2021-09-21 11:10
Ongoing investigation with:
http://localhost:4000/aex9/balances/ct_2bwK4mxEe3y9SazQRPXE8NdXikSTqF2T9FhNrawRzFA21yacTo
http://localhost:4000/aex9/balances/account/ak_2CuCtmoExsuW7iG5BbRAoncSZAoZt8Abu21qrPUhqfFNin75iL
http://localhost:4000/aex9/transfers/to/ak_2CuCtmoExsuW7iG5BbRAoncSZAoZt8Abu21qrPUhqfFNin75iL

The Aex9AccountPresence is not found for the cases where `/balances/account/:aid` result is `[]`

**Comment by jyeshe** [comment] 2021-09-21 11:11
`aex9_transfer_event_hash/0` used in the sync is a constant (not context sensitive).

**Comment by jyeshe** [comment] 2021-09-23 19:51
The `/balances/account/:aid` already uses the contract state for the balance:
https://github.com/aeternity/ae_mdw/blob/c89ec1880726cac5239a09996b142f1b9e024b0b/lib/ae_mdw_web/controllers/aex9_controller.ex#L219
`DBN.aex9_balance` performs a contract call likewise the `/balances/:contract_id`:
https://github.com/aeternity/ae_mdw/blob/c89ec1880726cac5239a09996b142f1b9e024b0b/lib/ae_mdw/contract.ex#L110
https://github.com/aeternity/ae_mdw/blob/c89ec1880726cac5239a09996b142f1b9e024b0b/lib/ae_mdw/contract.ex#L153

The issue is in the association of the account with the contract (i.e missing record in `Aex9AccountPresence` table). This has a correlation to the fact that the contract calls that have transferred tokens to the account are not recorded in the `Model.ContractCall` table. One can check that replaying the sync for the microblocks recorded in this `Model.ContractCall` table (branch `dbg-aex9-empty-balances` for this debugging).

**Closed** 2021-10-01 16:57 UTC
Labels: bug
